const items = [['brdnypants.png', 'Burgundy pants'],['brgndydrs.png', 'Burgundy dress'],['crmcropswtr.png', 'Cream crop sweater'],['flimsynightie.png', 'Flimsy nightie'],['rnbwombredrs.png', 'Rainbow ombré dress'],['pnkswtr.png', 'Pink sweater'],['slvsilkset.png', 'Silver silk set'],['strpbbydolldrs.png', 'Striped baby-doll dress'],['tanminiskrt.png', 'Tan mini skirt'],['whitevesttop.png', 'White vest top'],['blackwedges.png', 'Black wedges'],['blkpants.png', 'Black pants'],['docmartens.png', 'Doc Martens'],['blacklstop.png', 'Black long-sleeve top'],['whtblouse.png', 'White blouse'],['pnkminidrs.png', 'Pink dress'],['brgndyskrt.png', 'Burgundy skirt'],['flimsynightieblue.png', 'Blue slip dress'],['redberet.png', 'Red beret']];
const hairstyles = [['casualbunHAIR.png', 'Casual bun'],['lowbunHAIR.png', 'Low bun'],['downHAIR.png', 'Down'],['bangsdownHAIR.png', 'Bangs down'],['ponytailHAIR.png', 'Ponytail'],['y2kbunHAIR.png', 'Y2K bun'],['wavybobHAIR.png', 'Wavy bob']];
const rack = document.querySelector('#rack'), hairRack = document.querySelector('#hair-rack'), board = document.querySelector('#board'), layers = document.querySelector('#layers'), emptyLayers = document.querySelector('#empty-layers'), hint = document.querySelector('#hint'), nightieBubble = document.querySelector('#nightie-bubble');
const BOARD_W = 300, BOARD_H = 432;
let z = 3;
const hairLayer = document.createElement('img'); hairLayer.className = 'hair-piece'; hairLayer.alt = 'Casual bun hairstyle'; hairLayer.src = `assets/${hairstyles[0][0]}`;
board.append(hairLayer);

function dataFor(item) { return {src:item[0], name:item[1], w:item[2] || 1, h:item[3] || 1, x:item[4] || 0, y:item[5] || 0}; }
function placedPieces() { return [...board.querySelectorAll('.piece')].sort((a,b) => Number(a.style.zIndex) - Number(b.style.zIndex)); }
function updateLayers() { const pieces=placedPieces(); layers.replaceChildren(); emptyLayers.hidden=pieces.length>0; [...pieces].reverse().forEach(piece=>{const row=document.createElement('div');row.className='layer-row';const name=document.createElement('span');name.textContent=piece.dataset.name;const forward=document.createElement('button');forward.type='button';forward.textContent='↑';forward.title='Bring forward';const back=document.createElement('button');back.type='button';back.textContent='↓';back.title='Send backward';forward.addEventListener('click',()=>changeLayer(piece,1));back.addEventListener('click',()=>changeLayer(piece,-1));row.append(name,forward,back);layers.append(row)}); }
function changeLayer(piece,direction) { const pieces=placedPieces(),index=pieces.indexOf(piece),other=pieces[index+direction];if(!other)return;const currentZ=piece.style.zIndex;piece.style.zIndex=other.style.zIndex;other.style.zIndex=currentZ;updateLayers(); }
function makePiece(data,x=data.x,y=data.y) { const image=document.createElement('img');image.src=`assets/${data.src}`;image.alt=data.name;image.className='piece';image.style.width=`${Math.round(data.w*BOARD_W)}px`;image.style.height=`${Math.round(data.h*BOARD_H)}px`;image.style.zIndex=++z;image.dataset.name=data.name;image.dataset.snapX=data.x;image.dataset.snapY=data.y;image.dataset.w=data.w;image.dataset.h=data.h;image.addEventListener('pointerdown',beginPieceDrag);board.append(image);place(image,x,y);hint.hidden=true;updateLayers();return image; }
hairstyles.forEach(([src,name],index)=>{const button=document.createElement('button');button.type='button';button.className='hair-choice';button.innerHTML=src?`<img src="assets/${src}" alt=""><span>${name}</span>`:`<span>${name}</span>`;if(index===0)button.classList.add('active');button.addEventListener('click',()=>{hairLayer.src=src?`assets/${src}`:'';hairRack.querySelectorAll('.hair-choice').forEach(choice=>choice.classList.remove('active'));button.classList.add('active')});hairRack.append(button)});
items.forEach(item=>{const data=dataFor(item),button=document.createElement('button');button.type='button';button.className='garment';button.innerHTML=`<img src="assets/${data.src}" alt=""><span>${data.name}</span>`;button.addEventListener('click',()=>{if(button.dataset.ignoreClick){delete button.dataset.ignoreClick;return}makePiece(data);if(data.name==='Flimsy nightie')nightieBubble.hidden=false});button.addEventListener('pointerdown',event=>{if(window.matchMedia('(max-width:900px)').matches)return;button.dataset.ignoreClick='true';beginRackDrag(event,data)});rack.append(button)});
function boardPoint(event) { const r=board.getBoundingClientRect();return {x:(event.clientX-r.left)/r.width,y:(event.clientY-r.top)/r.height}; }
function autoScrollDuringDrag(event) { const edge=85, amount=26;if(event.clientY<edge)window.scrollBy(0,-amount);else if(event.clientY>window.innerHeight-edge)window.scrollBy(0,amount); }
function place(piece,x,y) { piece.style.left=`${Math.round(x*BOARD_W)}px`;piece.style.top=`${Math.round(y*BOARD_H)}px`; }
function snap(piece,x,y) { const sx=Number(piece.dataset.snapX),sy=Number(piece.dataset.snapY);return Math.hypot(x-sx,y-sy)<.16?{x:sx,y:sy,snapped:true}:{x,y,snapped:false}; }
function beginPieceDrag(event) { event.preventDefault();const piece=event.currentTarget,point=boardPoint(event),left=parseFloat(piece.style.left)/BOARD_W,top=parseFloat(piece.style.top)/BOARD_H;piece.style.zIndex=++z;updateLayers();piece.classList.add('dragging');const offset={x:point.x-left,y:point.y-top};piece.setPointerCapture(event.pointerId);const move=e=>{autoScrollDuringDrag(e);const p=boardPoint(e);place(piece,p.x-offset.x,p.y-offset.y)};const up=e=>{const p=boardPoint(e),done=snap(piece,p.x-offset.x,p.y-offset.y);place(piece,done.x,done.y);if(piece.dataset.name==='Flimsy nightie'&&done.snapped)nightieBubble.hidden=false;piece.classList.remove('dragging');piece.removeEventListener('pointermove',move);piece.removeEventListener('pointerup',up);piece.removeEventListener('pointercancel',up);updateLayers()};piece.addEventListener('pointermove',move);piece.addEventListener('pointerup',up);piece.addEventListener('pointercancel',up); }
function beginRackDrag(event,data) { if(event.pointerType==='mouse'&&event.button!==0)return;event.preventDefault();const piece=makePiece(data,1.25,1.25);const move=e=>{autoScrollDuringDrag(e);const p=boardPoint(e);place(piece,p.x-data.w/2,p.y-data.h/2)};const up=e=>{const p=boardPoint(e),x=p.x-data.w/2,y=p.y-data.h/2,done=snap(piece,x,y);place(piece,done.x,done.y);if(piece.dataset.name==='Flimsy nightie'&&done.snapped)nightieBubble.hidden=false;window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);updateLayers()};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up,{once:true});move(event); }
document.querySelector('#reset').addEventListener('click',()=>{board.querySelectorAll('.piece').forEach(piece=>piece.remove());hint.hidden=false;nightieBubble.hidden=true;updateLayers()});
document.querySelector('#close-bubble').addEventListener('click',()=>{nightieBubble.hidden=true});
