const items = [['brdnypants.png', 'Burgundy pants'],['brgndydrs.png', 'Burgundy dress'],['crmcropswtr.png', 'Cream crop sweater'],['flimsynightie.png', 'Flimsy nightie'],['rnbwombredrs.png', 'Rainbow ombré dress'],['pnkswtr.png', 'Pink sweater'],['slvsilkset.png', 'Silver silk set'],['strpbbydolldrs.png?v=20260922-1', 'Striped baby-doll dress'],['tanminiskrt.png?v=20260925-1', 'Tan mini skirt'],['whitevesttop.png?v=20260922-1', 'White vest top'],['blackwedges.png', 'Black wedges'],['blkpants.png', 'Black pants'],['docmartens.png', 'Doc Martens'],['blacklstop.png?v=20260925-2', 'Black long-sleeve top'],['whtblouse.png', 'White blouse'],['pnkminidrs.png', 'Pink dress'],['brgndyskrt.png', 'Burgundy skirt'],['flimsynightieblue.png', 'Blue slip dress'],['redberet.png', 'Red beret'],['maryjanes.png', 'Mary Janes'],['maryjaneheels.png', 'Mary Jane heels'],['frillysocks.png', 'Frilly socks'],['motojacket.png?v=20260922-1', 'Motorcycle jacket'],['cherry.png', 'Cherry bird'],['navycutiebikini.png', 'Navy cutie bikini'],['yellowfloralbikini.png', 'Yellow floral bikini'],['silverheels.png', 'Silver heels'],['heidi1.png?v=20260922-3', 'Heidi', 1, 1, 0, 0, 'heidi2.png?v=20260922-7'],['tancardigan.png?v=20260922-1', 'Tan cardigan'],['bfbuttondownblue2.png', 'Blue button-down', 1, 1, 0, 0, 'bfbuttondownblue1.png?v=20260925-1', true],['lowrisebfjean.png', 'Low-rise boyfriend jeans'],['bfbuttondowngreenstripe2.png', 'Green striped button-down', 1, 1, 0, 0, 'bfbuttondowngreenstripe1.png?v=20260925-1', true]];
const hairstyles = [['casualbunHAIR.png', 'Casual bun'],['lowbunHAIR.png', 'Low bun'],['downHAIR.png', 'Down'],['bangsdownHAIR.png', 'Bangs down'],['ponytailHAIR.png', 'Ponytail'],['y2kbunHAIR.png', 'Y2K bun'],['wavybobHAIR.png', 'Wavy bob']];
const rack = document.querySelector('#rack'), hairRack = document.querySelector('#hair-rack'), board = document.querySelector('#board'), layers = document.querySelector('#layers'), emptyLayers = document.querySelector('#empty-layers'), hint = document.querySelector('#hint'), nightieBubble = document.querySelector('#nightie-bubble');
const BOARD_W = 300, BOARD_H = 432;
const bubbleText = nightieBubble.querySelector('p');
let z = 3;
const hairLayer = document.createElement('img'); hairLayer.className = 'hair-piece'; hairLayer.alt = 'Casual bun hairstyle'; hairLayer.src = `assets/${hairstyles[0][0]}`;
board.append(hairLayer);

function dataFor(item) { return {src:item[0], name:item[1], w:item[2] || 1, h:item[3] || 1, x:item[4] || 0, y:item[5] || 0, frontSrc:item[6] || '', layeredBack:Boolean(item[7])}; }
function placedPieces() { return [...board.querySelectorAll('.piece:not([data-layer-hidden="true"])')].sort((a,b) => Number(a.style.zIndex) - Number(b.style.zIndex)); }
function pieceGroup(piece) { const group=piece.dataset.group;return group?[...board.querySelectorAll(`.piece[data-group="${group}"]`)]:[piece]; }
function removePiece(piece) { pieceGroup(piece).forEach(part=>part.remove()); }
function showPieceMessage(name) { const message=name==='Flimsy nightie'?'i need to get dressed i have this flimsy, sleeveless nightie on lol':name==='Cherry bird'?'girl water':'';if(!message)return;bubbleText.textContent=message;nightieBubble.hidden=false; }
function updateLayers() { const pieces=placedPieces(); layers.replaceChildren(); emptyLayers.hidden=pieces.length>0; [...pieces].reverse().forEach(piece=>{const row=document.createElement('div');row.className='layer-row';const name=document.createElement('span');name.textContent=piece.dataset.name;const forward=document.createElement('button');forward.type='button';forward.textContent='↑';forward.title='Bring forward';const back=document.createElement('button');back.type='button';back.textContent='↓';back.title='Send backward';const remove=document.createElement('button');remove.type='button';remove.textContent='×';remove.title=`Remove ${piece.dataset.name}`;remove.className='remove-layer';forward.addEventListener('click',()=>changeLayer(piece,1));back.addEventListener('click',()=>changeLayer(piece,-1));remove.addEventListener('click',()=>{removePiece(piece);if(!board.querySelector('.piece'))hint.hidden=false;updateLayers()});if(piece.dataset.fixedSplit==='true')row.append(name,remove);else row.append(name,remove,forward,back);layers.append(row)}); }
function changeLayer(piece,direction) { if(piece.dataset.fixedSplit==='true')return;const pieces=placedPieces(),index=pieces.indexOf(piece),other=pieces[index+direction];if(!other)return;const currentZ=piece.style.zIndex;piece.style.zIndex=other.style.zIndex;other.style.zIndex=currentZ;updateLayers(); }
function makePiece(data,x=data.x,y=data.y) { const image=document.createElement('img');image.src=`assets/${data.frontSrc||data.src}`;image.alt=data.name;image.className='piece';image.style.width=`${data.w*100}%`;image.style.height=`${data.h*100}%`;image.style.zIndex=data.frontSrc?100000:++z;image.dataset.name=data.name;image.dataset.snapX=data.x;image.dataset.snapY=data.y;image.dataset.w=data.w;image.dataset.h=data.h;if(data.frontSrc){const group=`split-${Date.now()}-${Math.random().toString(36).slice(2)}`;const back=document.createElement('img');back.src=`assets/${data.src}`;back.alt='';back.className='piece';back.style.width=image.style.width;back.style.height=image.style.height;back.dataset.group=group;back.dataset.splitRole='back';image.dataset.group=group;image.dataset.splitRole='front';image.style.pointerEvents='none';if(data.layeredBack){back.style.zIndex=++z;back.dataset.name=data.name;back.dataset.snapX=data.x;back.dataset.snapY=data.y;back.dataset.w=data.w;back.dataset.h=data.h;back.addEventListener('pointerdown',beginPieceDrag);image.style.zIndex=100000;image.dataset.layerHidden='true'}else{back.style.zIndex=1;back.dataset.layerHidden='true';back.style.pointerEvents='none';image.dataset.fixedSplit='true'}board.append(back,image)}else{image.addEventListener('pointerdown',beginPieceDrag);board.append(image)}place(image,x,y);hint.hidden=true;updateLayers();return image; }
hairstyles.forEach(([src,name],index)=>{const button=document.createElement('button');button.type='button';button.className='hair-choice';button.setAttribute('aria-label',name);button.innerHTML=`<span>${index+1}</span>`;if(index===0)button.classList.add('active');button.addEventListener('click',()=>{hairLayer.src=src?`assets/${src}`:'';hairRack.querySelectorAll('.hair-choice').forEach(choice=>choice.classList.remove('active'));button.classList.add('active')});hairRack.append(button)});
items.forEach(item=>{const data=dataFor(item),button=document.createElement('button');button.type='button';button.className='garment';button.innerHTML=`<img src="assets/${data.src}" alt=""><span>${data.name}</span>`;button.addEventListener('click',()=>{if(button.dataset.ignoreClick){delete button.dataset.ignoreClick;return}makePiece(data);showPieceMessage(data.name)});button.addEventListener('pointerdown',event=>{if(window.matchMedia('(max-width:900px)').matches)return;button.dataset.ignoreClick='true';beginRackDrag(event,data)});rack.append(button)});
function boardPoint(event) { const r=board.getBoundingClientRect();return {x:(event.clientX-r.left)/r.width,y:(event.clientY-r.top)/r.height}; }
function autoScrollDuringDrag(event) { const edge=85, amount=26;if(event.clientY<edge)window.scrollBy(0,-amount);else if(event.clientY>window.innerHeight-edge)window.scrollBy(0,amount); }
function place(piece,x,y) { pieceGroup(piece).forEach(part=>{part.style.left=`${x*100}%`;part.style.top=`${y*100}%`}); }
function snap(piece,x,y) { const sx=Number(piece.dataset.snapX),sy=Number(piece.dataset.snapY);return Math.hypot(x-sx,y-sy)<.16?{x:sx,y:sy,snapped:true}:{x,y,snapped:false}; }
function beginPieceDrag(event) { event.preventDefault();const piece=event.currentTarget,point=boardPoint(event),left=parseFloat(piece.style.left)/100,top=parseFloat(piece.style.top)/100;piece.style.zIndex=++z;updateLayers();piece.classList.add('dragging');const offset={x:point.x-left,y:point.y-top};piece.setPointerCapture(event.pointerId);const move=e=>{autoScrollDuringDrag(e);const p=boardPoint(e);place(piece,p.x-offset.x,p.y-offset.y)};const up=e=>{const p=boardPoint(e),done=snap(piece,p.x-offset.x,p.y-offset.y);place(piece,done.x,done.y);if(done.snapped)showPieceMessage(piece.dataset.name);piece.classList.remove('dragging');piece.removeEventListener('pointermove',move);piece.removeEventListener('pointerup',up);piece.removeEventListener('pointercancel',up);updateLayers()};piece.addEventListener('pointermove',move);piece.addEventListener('pointerup',up);piece.addEventListener('pointercancel',up); }
function beginRackDrag(event,data) { if(event.pointerType==='mouse'&&event.button!==0)return;event.preventDefault();const piece=makePiece(data,1.25,1.25);const move=e=>{autoScrollDuringDrag(e);const p=boardPoint(e);place(piece,p.x-data.w/2,p.y-data.h/2)};const up=e=>{const p=boardPoint(e),x=p.x-data.w/2,y=p.y-data.h/2,done=snap(piece,x,y);place(piece,done.x,done.y);if(done.snapped)showPieceMessage(piece.dataset.name);window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);updateLayers()};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up,{once:true});move(event); }
document.querySelector('#reset').addEventListener('click',()=>{board.querySelectorAll('.piece').forEach(piece=>piece.remove());hint.hidden=false;nightieBubble.hidden=true;updateLayers()});
document.querySelector('#close-bubble').addEventListener('click',()=>{nightieBubble.hidden=true});

const themeChoices = document.querySelectorAll('.theme-choice');
function setTheme(theme) {
  document.body.dataset.theme = theme;
  themeChoices.forEach(choice => {
    const selected = choice.dataset.theme === theme;
    choice.classList.toggle('active', selected);
    choice.setAttribute('aria-pressed', selected);
  });
  localStorage.setItem('paola-theme', theme);
}
themeChoices.forEach(choice => choice.addEventListener('click', () => setTheme(choice.dataset.theme)));
const savedTheme = localStorage.getItem('paola-theme');
if (savedTheme && document.querySelector(`[data-theme="${savedTheme}"]`)) setTheme(savedTheme);
